{$op_names = [
	'BONUS'=>'Bonus',
	'PENALTY'=>'Penalty',
	'CASHIN'=>'Recharge',
	'CASHOUT'=>'Withdrawal',
	'EX'=>'Outgoing exchange',
	'EXIN'=>'Incoming exchange',
	'TR'=>'Transfer',
	'TRIN'=>'Income',
	'BUY'=>'Buy',
	'SELL'=>'Sell',
	'BUY2'=>'Service',
	'SELL2'=>'Service',
	'REF'=>'Refferal bonus',
	'GIVE'=>'Deposit',
	'TAKE'=>'Withdrawal',
	'CALCIN'=>'Accrual',
	'CALCOUT'=>'Calcout'
] scope='global'}
{$op_statuses = [
	0=>'Confirmation awaiting',
	1=>'Rechargement awaiting',
	2=>'Completion awaiting',
	3=>'Done',
	4=>'Declined',
	5=>'Cancelled'
] scope='global'}
{$op_sums = [
	'BONUS'=>'Sum',
	'PENALTY'=>'Sum',
	'CASHIN'=>'Sum to recharge',
	'CASHOUT'=>'Sum to withdraw',
	'EX'=>'Sum to exchange',
	'EXIN'=>'Sum recieved',
	'TR'=>'Sum to recieve',
	'TRIN'=>'Recieved sum',
	'BUY'=>'Sum',
	'SELL'=>'Sum',
	'BUY2'=>'Sum',
	'SELL2'=>'Sum',
	'REF'=>'Sum',
	'GIVE'=>'Sum of deposit',
	'TAKE'=>'Sum to recieve',
	'CALCIN'=>'Sum',
	'CALCOUT'=>'Sum'
] scope='global'}
